#!/command/with-contenv bash
# shellcheck shell=bash

set -euo pipefail

if [[ "${WEBSERVER-false}" == 'false' ]]; then
  echo "Webserver disabled."
  exec s6-svc -Od .
fi

bind_ip="${WEBSERVER_LISTEN_IP-0.0.0.0}"
port="${WEBSERVER_PORT-8000}"
echo "Starting webserver on ${bind_ip}:${port}."
exec darkhttpd /var/www/localhost/htdocs --chroot --uid darkhttpd --gid www-data --addr "${bind_ip}" --port "${port}" --no-listing --no-server-id
